name : CI + CD 

on : 
  push:  
      branches: [ "main"]

jobs :
   Pipeline :
     runs-on: ubuntu-latest

     steps :
      - uses : actions/checkout@v4
      
      - name : Build Docker image
        run : docker build -t conversor-archivos  
   
  
